using UnityEngine;

public class Test : MonoBehaviour
{
    [SerializeField]
    private float _jumpPower = 4;
    private Rigidbody2D Rb { get; set; }
    private bool Grounded { get; set; } = false;
    private bool PrevGrounded { get; set; } = false;
    private bool Jumped { get; set; } = false;

    private void Start()
    {
        Rb = GetComponent<Rigidbody2D>();
    }

    private void Update()
    {
        if (Input.GetKeyDown(KeyCode.Space))
        {
            Jump();
        }
    }

    /// <summary>
    /// ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÉGï¿½ï¿½Ä‚ï¿½ï¿½é‚©ï¿½ğ”»’è‚·ï¿½ï¿½
    /// </summary>
    /// <returns>ï¿½ï¿½ï¿½ï¿½ï¿½ÉGï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½trueï¿½Aï¿½ï¿½ï¿½ï¿½ï¿½Gï¿½ï¿½Ä‚ï¿½ï¿½È‚ï¿½ï¿½ï¿½ï¿½false</returns>
    

    public void Jump()
    {
        if (!Jumped)
        {
            Jumped = true;
            Rb.linearVelocity = new Vector2(Rb.linearVelocity.x, _jumpPower);
            Invoke("EndGtounded", 0.2f);
        }
       
        
    }
    private void EndGtounded()
    {
        Jumped = false;
    }
}
